###
//GUARDAR DATOS EN LA BASE DE DATOS
POST http://localhost:4000/api/cursos HTTP/1.1
Content-Type: application/json

    {
    "descripcion": "Redes",
    "fecha_inicio": "10/10/2022",
    "hora_inicio": "10:00"
    }



//EXTRAER LOS DATOS DE LA BASE DE DATOS
###
GET http://localhost:4000/api/cursos HTTP/1.1

//EXTRAER SOLO UN DATO POR MEDIO DE L ID
###
GET http://localhost:4000/api/cursos/634a37d54ad9f58984dbd50a HTTP/1.1

//PARA EDITAR UN DATOS POR MEDIO DE LA ID
###

PUT http://localhost:4000/api/cursos/634a37d54ad9f58984dbd50a HTTP/1.1
Content-Type: application/json

    {
    "descripcion": "Seguridad1",
    "fecha_inicio": "5/12/2022",
    "hora_inicio": "11:00"
    }

//ELIMINAR DATOS POR MEDIO DE LA ID
###
DELETE  http://localhost:4000/api/cursos/634a37d54ad9f58984dbd50a HTTP/1.1


// PETICINES DEL ASPIRANTE

//CREA LOS DATOS Y LOS GUARDA EN LA BASE DE DATOS
###
POST http://localhost:4000/api/aspirantes HTTP/1.1
Content-Type: application/json

    {
    "nombre": "Maria",
    "identificacion": "1310988751",
    "correo": "maria@gmail.com"
    }



// HACE LA PETICION DE TODO LOS DATOS DE LA BASE DE DATOS
###
GET http://localhost:4000/api/aspirantes HTTP/1.1

//HACE LA PETICION DE LOS DATOS SOLO POR ID
###
GET http://localhost:4000/api/aspirantes/634a35ec4ad9f58984dbd505 HTTP/1.1

//EDITA LOS DATOS DE LA BASE DE DATOS POR ID 
###

PUT http://localhost:4000/api/aspirantes/634a35ec4ad9f58984dbd505 HTTP/1.1
Content-Type: application/json

    {
    "nombre": "Panchis",
    "identificacion": "1319876545",
    "correo": "panchis@gmail.com"
    }

//ELIMINA LOS DATOS DE LA BASE DE DATOS POR ID
###
DELETE  http://localhost:4000/api/aspirantes/634a35ec4ad9f58984dbd505 HTTP/1.1

// PETICINES DE LAS INSCRIPCIONES

//CREA LOS DATOS Y LOS GUARDA EN LA BASE DE DATOS
###
POST http://localhost:4000/api/inscripciones HTTP/1.1
Content-Type: application/json

    {
    "fecha": "8/11/2022",
    "hora": "14:00",
    "valor_cancelar": "$ 21"
    }

// HACE LA PETICION DE TODO LOS DATOS DE LA BASE DE DATOS
###
GET http://localhost:4000/api/inscripciones HTTP/1.1

//HACE LA PETICION DE LOS DATOS SOLO POR ID
###
GET http://localhost:4000/api/inscripciones/634a3b3b7a1bc5f09cf6b4e9 HTTP/1.1

//EDITA LOS DATOS DE LA BASE DE DATOS POR ID 
###

PUT http://localhost:4000/api/inscripciones/634a3b3b7a1bc5f09cf6b4e9 HTTP/1.1
Content-Type: application/json

    {
    "Fecha": "10/10/2022",
    "Hora": "10:00",
    "valor_cancelar": "$ 25"
    }

//ELIMINA LOS DATOS DE LA BASE DE DATOS POR ID
###
DELETE  http://localhost:4000/api/inscripciones/634a3b3b7a1bc5f09cf6b4e9 HTTP/1.1